### ISSUE TITLE
Couldn't create a map. Also not sure where to place map schematic files.

### ISSUE THREAD

**Issue by LouisRitchie** [LielAmar/Spleef#1]
Hello there! I just found your project and it's great. I am not able to make use of it yet, though. I'm a bit new to installing and managing Minecraft server plugins.

OK, so here's what I did.

- I cloned the project to my filesystem
- I opened the project in Eclipse
- I added the Spigot and WorldEdit libraries
- I exported the project to a .jar, using compiler version 11.
- I copied the exported .jar to my server and reloaded my server. **I receive the error: "Failed to load 0 maps!"** Plugin loads without issue.
- Success! I am able to run `/spleef` command as an admin.
- try to create a new map, and there is an unhandled exception. I used the command `/spleef map create bugworld`. **error below**
- I went looking for maps to install, and I found [6 Spleef maps here](https://www.planetminecraft.com/project/spleef-arena-bundle-6-maps/)

Now that I've downloaded those maps, I don't know where to put them.

Let me know if I've made any obvious mistakes. I'd love to start playing Spleef on my server using your great plugin.

Anyway great project and I'm able to contribute to help fix any issues.

The full error message:

```
org.bukkit.command.CommandException: Unhandled exception executing command 'spleef' in plugin Spleef v1.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/WorldEditException
        at net.lielamar.spleef.managers.GameManager.addMap(GameManager.java:264) ~[?:?]
        at net.lielamar.spleef.commands.spleef.SubCommandMap.onCommand(SubCommandMap.java:47) ~[?:?]
        at net.lielamar.spleef.commands.spleef.SpleefCommand.onCommand(SpleefCommand.java:76) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        ... 18 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.WorldEditException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at net.lielamar.spleef.managers.GameManager.addMap(GameManager.java:264) ~[?:?]
        at net.lielamar.spleef.commands.spleef.SubCommandMap.onCommand(SubCommandMap.java:47) ~[?:?]
        at net.lielamar.spleef.commands.spleef.SpleefCommand.onCommand(SpleefCommand.java:76) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        ... 18 more

```

**Comment by LielAmar** [comment]
Hi LouisRitchie, thank you for contacting me :)

I am sorry for not making it clearer, but the schematic files should be located at the Spleef subfolder inside of your /plugins folder.
After you have your schematic in the folder, all you need to do is to run `/spleef map create Test` and it'll create an arena for you.
From there, you can use the commands to set all the arena variables (such as minimum Y, spawn locations, and more).

As for the error - This error means the plugin was not able to locate WorldEdit, or at least the right one.
WorldEdit has been changed quite a bit, so make sure to use the latest version of it.
You can download the WorldEdit version I use from https://lielamar.com/other/WorldEdit1.16.2.jar

**Comment by LouisRitchie** [comment]
I don't think I'll be able to make use of your Spleef plugin unfortunately. I can't find a version of WorldEdit1.16.2.jar on the official downloads page. I did install the latest release candidate, WorldEdit v7.2.0rc2. I reloaded my plugins, I ran `spleef map create <map-name>` and I received this error:

```
org.bukkit.command.CommandException: Unhandled exception executing command 'spleef' in plugin Spleef v1.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at net.lielamar.spleef.moduels.Game.<init>(Game.java:22) ~[?:?]
        at net.lielamar.spleef.managers.GameManager.addMap(GameManager.java:266) ~[?:?]
        at net.lielamar.spleef.commands.spleef.SubCommandMap.onCommand(SubCommandMap.java:47) ~[?:?]
        at net.lielamar.spleef.commands.spleef.SpleefCommand.onCommand(SpleefCommand.java:76) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        ... 18 more
Caused by: java.lang.NullPointerException
        at net.lielamar.spleef.utils.GlobalVariables.<clinit>(GlobalVariables.java:7) ~[?:?]
        at net.lielamar.spleef.moduels.Game.<init>(Game.java:22) ~[?:?]
        at net.lielamar.spleef.managers.GameManager.addMap(GameManager.java:266) ~[?:?]
        at net.lielamar.spleef.commands.spleef.SubCommandMap.onCommand(SubCommandMap.java:47) ~[?:?]
        at net.lielamar.spleef.commands.spleef.SpleefCommand.onCommand(SpleefCommand.java:76) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
        ... 18 more
```

I'm not comfortable running a .jar that I downloaded from your website.

**Comment by LielAmar** [comment]
7.2.0 is the version I am using :)
The error is a complete different problem. I will fix it later today :)

**Comment by LouisRitchie** [comment]
Thanks! Lemme know when you fix it and I'll compile & run it.

**Comment by LielAmar** [comment]
Fixed the bug. Shouldn't happen now :)
Anyways, make sure your config is up to date and contains all of the variables needed for the game to run ^^
